package xyz.refinedev.practice.profile.settings;

public enum ProfileSettingsType {

      TOGGLESCOREBOARD, TOGGLECPSONSCOREBOARD, TOGGLEPINGONSCOREBOARD, TOGGLESHOWPLAYERS, TOGGLESPECTATORS, TOGGLEDUELREQUESTS,
      TOGGLETABSTYLE, TOGGLEPINGFACTOR, TOGGLEDROPPROTECT, TOGGLETOURNAMENTMESSAGES

}
