package xyz.refinedev.practice.profile.settings;

public enum SettingsType {

      TOGGLESCOREBOARD, TOGGLECPSONSCOREBOARD, TOGGLEPINGONSCOREBOARD, TOGGLESHOWPLAYERS, TOGGLESPECTATORS, TOGGLEDUELREQUESTS,
      TOGGLETABSTYLE, TOGGLEPINGFACTOR, TOGGLELIGHTNING, TOGGLEDROPPROTECT, TOGGLETOURNAMENTMESSAGES

}
