main: me.drizzy.practice.Array
name: Array
version: 1.0
authors: ["Nick", "Drizzy"]
depend:
  - ProtocolLib
softdepend:
  - HolographicDisplays
  - PlaceholderAPI
  - MizuCore
  - ZoomCore
  - AquaCore
  - Hestia
